scrape_configs:

  - job_name: 'Product Service Mitocode'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.18.16:9020']
        labels:
          application: 'Product Service Microservice Scrapping'

  - job_name: 'User Service Mitocode'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.18.16:9030']
        labels:
          application: 'User Service Microservice Scrapping'

  - job_name: 'Client Service Circuit Breaker'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.18.16:9010']
        labels:
          application: 'Client Service Microservice Scrapping'